version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver-carrefour
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "1433:1433"
    networks:
      - network-carrefour
    volumes:
      - sqlserver_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-carrefour
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-carrefour

  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: redis-carrefour
  #   ports:
  #     - "6379:6379"
  #     - "8085:8085"
  #   networks:
  #     - bridge

  # cashflowapi:
  #   build:
  #     context: .
  #     dockerfile: ./CashFlowAPI/CashFlowAPI/Dockerfile
  #   container_name: cashflowapi
  #   depends_on:
  #     - sqlserver
  #     - rabbitmq
  #   #   - redis
  #   environment:
  #     ConnectionStrings__SqlServer: "Server=sqlserver;Database=BancoCarrefour;User Id=sa;Password=1q2w3e4r@#$;"
  #     RabbitMQ__Host: rabbitmq
  #     # Redis__Host: redis-carrefour
  #   networks:
  #     - network-carrefour
  #   ports:
  #     - "5286:5286"

  # cashflowworker:
  #   build:
  #     context: .
  #     dockerfile: ./CashFlowWorker/CashFlowWorker/Dockerfile
  #   container_name: cashflowworker
  #   depends_on:
  #   #   - sqlserver
  #     - rabbitmq
  #   #   - redis
  #   environment:
  #   #   ConnectionStrings__SqlServer: "Server=sqlserver-carrefour;Database=BancoCarrefour;User Id=sa;Password=1q2w3e4r@#$;"
  #     RabbitMQ__Host: rabbitmq
  #   #   Redis__Host: redis-carrefour
  #   networks:
  #     - network-carrefour

  balanceapi:
    build:
      context: .
      dockerfile: ./BalanceAPI/BalanceAPI/Dockerfile
    container_name: balanceapi
    depends_on:
      - sqlserver
      - rabbitmq
      # - redis
    environment:
      ConnectionStrings__SqlServer: "Server=sqlserver;Database=BancoCarrefour;User Id=sa;Password=1q2w3e4r@#$;"
      RabbitMQ__Host: rabbitmq
    #   Redis__Host: redis-carrefour
    networks:
      - network-carrefour
    ports:
      - "5041:5041"
      # - "7022"
    # healthcheck:
    #   test: ["CMD", "sqlserver", "ping", "-h", "localhost"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 10

networks:
  network-carrefour:
    driver: bridge

volumes:
  sqlserver_data:
